### ISSUE TITLE
The headerbar size is inconsistent between applications when using Pop Slim

### ISSUE THREAD

**Issue by ErikWallstrom** [pop-os/gtk-theme#102]
As the title says, the headerbar size varies depending on application/widgets in the headerbar. I have not noticed this in other themes, and I assume this is not intended. 

![screenshot from 2017-12-16 19-45-44](https://user-images.githubusercontent.com/15019604/34073446-71d464da-e29a-11e7-8716-a70b7dba40ea.png)
![screenshot from 2017-12-16 19-44-49](https://user-images.githubusercontent.com/15019604/34073447-72390ea8-e29a-11e7-93e3-34af3759dcb5.png)

```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - 3.22.26
 * Desktop environment - GNOME 3.26
 * Pop version - Pop Version 3.0 Beta 3
 ```

**Related Application and/or Shell theming (or name of widget)**

GtkHeaderBar (height)

In the pictures:

* Geary
* GNOME Tweaks
* Nautilus

**Comment by isantop** [comment]
Some applications use fixed sizes for some headerbar children, which aren't necessarily consistent across multiple applications. Since these are usually values hardcoded into either the application code or its CSS, these aren't generally things that can be worked around in the theme apart from making all headerbars have a minimum size larger than it currently is.

**Comment by isantop** [comment]
In testing with the new v4 release of the theme, I believe most of these cases have been eliminated. I'm thus marking this fix-committed.

**Comment by isantop** [comment]
Fixed in `master_cosmic`
