### ISSUE TITLE
Dialog button contrast

### ISSUE THREAD

**Issue by cassidyjames** [pop-os/gtk-theme#35]
Dialog buttons in both the GTK and Shell themes are a bit low-contrast. We should take a look and make sure they're contrast compliant and look good.

![shell](https://i1.wp.com/www.linuxbookpro.com/wp-content/uploads/2017/09/Screenshot-from-2017-09-29-12-50-58.png?resize=1200%2C675)

![GTK](https://i2.wp.com/www.linuxbookpro.com/wp-content/uploads/2017/09/Screenshot-from-2017-09-29-14-07-09.png?w=453)

[Reported by /u/joe4ska on Reddit](https://www.reddit.com/r/pop_os/comments/73ab6t/suggestion_dialog_buttons_need_more_contrast_pop/), but I agree with them.

**Comment by josephdickson** [comment]
If you have any questions about this Issue I'm the one who submitted it on reddit. I'll track it here.
Thanks for filing the bug report @cassidyjames

**Comment by Feichtmeier** [comment]
Chrome, GTK2 apps are also very low contrasted (didn't want necromance my old bug)

**Comment by isantop** [comment]
@Feichtmeier Can you post a screenshot or two demonstrating which parts are low-contrast? Also, which version of Chrome? It might be preferable to open a new issue, since these aren't necessarily related problems (GTK3 and Shell contrast is controlled by CSS, whereas Chrome and GTK2 use a combination of configuration files and SVG image assets)

**Comment by Feichtmeier** [comment]
@isantop thanks for looking into that again: https://github.com/system76/pop-gtk-theme/issues/38

**Comment by isantop** [comment]
This will be fixed in the upcoming 3.0 version of Pop GTK
