### ISSUE TITLE
Dark theme, Gnome Files: right-clicked item is black (and almost invisible since the background is black too)

### ISSUE THREAD

**Issue by abetkin** [pop-os/gtk-theme#387]
**Steps to reproduce:**
1. open Gnome Files
2. Right click on a file or folder (get the context menu)
![Screenshot from 2019-10-22 01-34-46](https://user-images.githubusercontent.com/2223279/67248534-7733b200-f46d-11e9-8b3e-e056c234cd27.png)

Actually, it feels even darker when context menu is shown, which is dark too

**Distribution:**
Pop-os

**Pop version:**
latest

**Comment by isantop** [comment]
I can't seem to replicate this issue here. The selected item _is_ dark when the window is in the  background, but it becomes light when the window is focused again.

![Screenshot from 2019-10-23 09-31-54](https://user-images.githubusercontent.com/5883565/67409640-1349e000-f578-11e9-90d6-ec3223a5b7c5.png)

**Comment by brs17** [comment]
> I can't seem to replicate this issue here. The selected item _is_ dark when the window is in the background, but it becomes light when the window is focused again.

I have been able to replicate this issue, I see @abetkin edited the title to mention it happens on right-click, which is how//when I was able to recreate this.

**Comment by isantop** [comment]
This appear to either be a limitation of nautilus, or using Adwaita as a base. This occurs in both Yaru-dark and Adwaita-dark
