### ISSUE TITLE
Pop!_OS 19.10 dark theme accent color

### ISSUE THREAD

**Issue by jupiterneptune** [pop-os/gtk-theme#399]
I've updated to version 19.10 and I've noticed that the accent color for the pop-dark theme is now blue/cyan instead of orange. I wonder why is this, because arguably the orange accent color is better for the eyes in conditions where you would use dark mode (late at night, night light enabled in GNOME etc.) and the blue color would be a worse fit. Maybe help us with at least a variation of pop-dark with original orange accent theme?

**Comment by isantop** [comment]
Because GTK uses the state of "Selected" as the way to distinguish the current sidebar item, using orange for the sidebar and blue for the selection creates a lot of problems, and doing them correctly basically requires patching each individual case where a sidebar is used manually. This caused inconsistencies with the old theme, which can create user confusion. The switch to basing the theme on Adwaita brought blue to the sidebar items, and this has been retained to help avoid these types of bugs in the future.

Orange is still used for controls which have a definite on/off state, like switches and check marks.
