### ISSUE TITLE
Dark variant shell theme doesn't appear in Gnome Tweaks dropdown

### ISSUE THREAD

**Issue by terencode** [pop-os/gtk-theme#436]
**Describe the problem:**
When installing the theme, I can see the dark variant on the Application theme dropdown but not on the gnome-shell theme one. 
It seems a symlink is missing.

**Steps to reproduce:**
1.  `meson buid && ninja -C build install`
2.  `ls -l  /usr/share/themes/Pop` and notice there is a symlink named `gnome-shell` pointing to `/usr/share/gnome-shell/theme/Pop`
3.  `ls -l  /usr/share/themes/Pop-dark` and notice no symlink is present
4. Add the missing symlink with `sudo ln -s /usr/share/gnome-shell/theme/Pop-dark /usr/share/themes/Pop-dark/gnome-shell`  and notice the dark shell variant is now available.

**Distribution:**
Arch Linux with gnome-shell 3.36

**Pop version:**
36320d17f945d38a71d231a5ac64a7f43e59d35d ~~with #421 merged.~~

**Comment by isantop** [comment]
#421 should not have been merged into your working branch, as that was a stale branch which was not ready for use (generally the latter will hold true for any draft PRs, and they shouldn't be expected to work.)

Do you have issues with the latest `master`?

**Comment by terencode** [comment]
Yeah I shouldn't have mentioned it anyway because it was the same behaviour without it.
Still the same issue with master in addition to the theme not shown at all for the applications dropdown.
#448 fixes the latter but the dark theme is still missing as shell theme and the symlink trick I use still works.

**Comment by AAnzel** [comment]
I just want to confirm everything @terencode said above. The bug is still persistent but the fix works.

**Comment by isantop** [comment]
This should be fixed in the latest version of the theme, since the gnome-shell dark theme is included in the `pop-gnome-shell-theme` package.

**Comment by neitsab** [comment]
Installing the latest 5.3.1 version with the [pop-gtk-theme](https://aur.archlinux.org/packages/pop-gtk-theme/) package in the AUR still results in a non-selectable dark shell theme due to the missing symlink. Once the symlink restored with `ln -s /usr/share/gnome-shell/theme/Pop-dark /usr/share/themes/Pop-dark/gnome-shell` dark shell theme is selectable and works properly.

Its [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pop-gtk-theme) uses the following build steps:

```bash
build() {
  cd "gtk-theme-${pkgver}"
  meson --prefix='/usr' build
  ninja -C build
}

package() {
  cd "gtk-theme-${pkgver}"
  DESTDIR="${pkgdir}" ninja -C build install
```
Is there anything that could explain the missing symlink or does the issue stem from the upstream tarball?
Thanks
