### ISSUE TITLE
Query: why does the theme require gtk2?

### ISSUE THREAD

**Issue by coxackie** [pop-os/gtk-theme#458]
I am puzzled as to why this theme there *requires* gtk2. I apologise if I am being naive - I understand that it themes gtk2 applications as well if any, but why require it? gtk4 is almost out there - if there is no particular reason, maybe drop the hard dependency?

**Comment by isantop** [comment]
As a member of the Adwaita theme family (via Yaru), the Pop theme inherits the same dependencies as our upstream projects, which include dependencies on `gtk2-engines-pixbuf` and `gtk2-engines-murrine`. These are required in order to ensure the necessary engines are installed for use with GTK2 applications.
