### ISSUE TITLE
Background of Lists changed into light gray instead of normal white (For example, files in list view)

### ISSUE THREAD

**Issue by TechnologyMan101** [pop-os/gtk-theme#475]
**Describe the problem:**
The background color of lists has changed to a light gray. It used to be white. Dark theme has a similar effect

Current (Light):
![Screenshot from 2020-10-11 20-43-27](https://user-images.githubusercontent.com/65311278/95716352-343f9100-0c20-11eb-8451-25ee9f74f9fb.png)

![Screenshot from 2020-10-12 00-16-28](https://user-images.githubusercontent.com/65311278/95716917-07d84480-0c21-11eb-88bb-894bed849f14.png)

Previous (Light):
![Screenshot from 2020-10-12 07-19-16](https://user-images.githubusercontent.com/65311278/95716956-158dca00-0c21-11eb-805a-6f6a17971392.png)

![Screenshot from 2020-10-12 07-19-24](https://user-images.githubusercontent.com/65311278/95716980-1de60500-0c21-11eb-8973-eb20db576179.png)

Current (Dark):
![Screenshot from 2020-10-12 00-24-16](https://user-images.githubusercontent.com/65311278/95717260-87feaa00-0c21-11eb-9d71-3f480944ebd8.png)

![Screenshot from 2020-10-12 00-24-36](https://user-images.githubusercontent.com/65311278/95717270-8af99a80-0c21-11eb-9882-a7f252f0c34c.png)

Previous (Dark):
![Screenshot from 2020-10-12 07-18-52](https://user-images.githubusercontent.com/65311278/95717320-9e0c6a80-0c21-11eb-9a9f-ce10d643a299.png)

![Screenshot from 2020-10-12 07-18-43](https://user-images.githubusercontent.com/65311278/95717329-a19ff180-0c21-11eb-8a28-bef9dcafea93.png)

**Steps to reproduce:**
1.  Open Files
2. Change into List view
3. Results

**Distribution:**
PRETTY_NAME="Pop!_OS 20.04 LTS"

**Pop version:**
Installed: 5.2.0~1599689740~20.04~11b9d22

**Comment by jacobgkau** [comment]
Confirmed this was a side effect of https://github.com/pop-os/gtk-theme/pull/470. `treeview.view` used to have a transparent background, now it uses `$bg_color` as its background color.

I ideally would have noticed this while testing that PR, but after taking screenshots to compare, it looks like the new background color matches what other two-pane apps use for the main content section:

![gtk-theme-i475-screenshot1](https://user-images.githubusercontent.com/7199422/95768839-35021280-0c74-11eb-89bd-0e5e3b4ccec7.png)

![gtk-theme-i475-screenshot2](https://user-images.githubusercontent.com/7199422/95768854-38959980-0c74-11eb-8c0a-9e80025a2863.png)

Although it is a bit inconsistent that the same color isn't used for the "Other Locations" page or icon view. In the case of the "Language Support" window, it seems like it makes sense for the list to be separated out from the rest of the tab with a different color, since the cursor needs to be inside of the list to scroll.

**Comment by TechnologyMan101** [comment]
So, would this be considered a non-issue or does this need fixing?

**Comment by isantop** [comment]
This is a bug, and the treeivews should have their background color set to `base_color` instead of `bg-color`. That should preserve the fix introduced with #470 without making the treeviews look weird.

**Comment by TechnologyMan101** [comment]
Saw that this got fixed. Will close this issue now.
