### ISSUE TITLE
application panel not transparent

### ISSUE THREAD

**Issue by dgoosens** [pop-os/gtk-theme#523]
Application panel is opaque, I expect it should be transparent as is the expose windows panel

![Screenshot from 2021-07-03 02-08-19](https://user-images.githubusercontent.com/1250047/124337587-a3408980-dba3-11eb-9888-943b76025f4a.png)

**Steps to reproduce:**

1. updated to Pop!_OS 21.04
2. WIN + A to open Application Panel

**Distribution:**

Pop!_OS 21.04

**Pop version:**

Installed: 5.3.3~1621633256~21.04~c5f700d

**Comment by jacobgkau** [comment]
The opaque background is intentional, see https://github.com/pop-os/gtk-theme/commit/e747d6829a1154672324af21dbc551c0de8c9512.

During user testing, the white text underneath the icons was not legible enough over a blurred view of the desktop and open windows. (The default desktop background includes a large white logo, but even if we changed the text color, there's no telling what a custom desktop background or the windows open behind the menu will look like.)

**Comment by dgoosens** [comment]
Hi @jacobgkau 

thanks for getting back at me and taking the time to explain...  
I can understand the issue... Although it would have been nice to give the user the choice, don't you think ?

1. Not everybody uses a  white background... Even less plausible,if they select the dark theme (like I did)
2. Personally, I barely ever look at the text in the App panel... 99% of the time, the app icon is sufficient to select the right application

Sadly, I don't think I'd be able to submit a PR for such a feature...   
Any chance to convert this into a Feature Request ?

dGo

**Comment by leviport** [comment]
> Although it would have been nice to give the user the choice, don't you think ?

There are plans to work on this in the future, so it's already on our radar.
