### ISSUE TITLE
text on inputs is un-noticeable

### ISSUE THREAD

**Issue by ItamarShDev** [pop-os/gtk-theme#69]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Reporter info**

```
 * Distribution - (run ```lsb_release -a```)
 * Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```)
 * Desktop environment - 
 * Pop version - (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```)
 ```

**Related Application and/or Shell theming (or name of widget)**
https://github.com/daniellandau/switcher
and on chrome and other inputs

**Actual issue**

![image](https://user-images.githubusercontent.com/953371/31862246-59fc28a2-b743-11e7-9673-b0e9e9eb7213.png)
![image](https://user-images.githubusercontent.com/953371/31862260-9993f544-b743-11e7-84f1-8d271b92845a.png)

**Steps to reproduce**

**Expected behavior**

**Behavior in Adwaita**

**Other Note (feature-request, question, etc...)**

**Comment by isantop** [comment]
This is something of a cantfix, because the real issue is certain applications not providing appropriate styling when working in specific situations. For example, when a website uses no styling for an entry widget and the browser renders a fallback, that shouldn't really be a system-based widget because that may completely clash with the look of the page, and may be unreadable depending on what styling is available. Toggles for light and dark themes are widely supported in several OSs now, so the browser should be doing the right thing already.

For that extension, it looks like the extension author needs to update the styling to use the theme foreground color, or implement some styling that works regardless of the text color. Themes can't style portions of extensions individually.
