### ISSUE TITLE
Some UI elements unreadable in Firefox

### ISSUE THREAD

**Issue by jlacroix82** [pop-os/gtk-theme#79]
Some fields are unreadable in Firefox. An example of this is in the AWS console, when configuring security groups. Other themes do not have this issue. Attached is a screenshot showing the problem. Text and background are both dark, which makes the text hard to read. I've seen other sites with this issue as well. Another example is the Debian package search page:

https://www.debian.org/distrib/packages#search_packages

![screenshot from 2017-10-31 15-44-43](https://user-images.githubusercontent.com/5324220/32279821-2212dd0a-bef0-11e7-96e4-d3cfda3e2c1f.png)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Reporter info**

```
 * Distribution - Ubuntu 17.10
 * Gtk+ 3.0 version - 3.22.11-0ubuntu3
 * Desktop environment - GNOME
 ```

**Actual issue**
Text is hard to read

**Steps to reproduce**
* Apply the POP theme
* Use the AWS console or visit a site with an affected text box

**Expected behavior**
Text should be easier to read

**Behavior in Adwaita**
Works fine

**Other Note (feature-request, question, etc...)**

**Comment by isantop** [comment]
I can't seem to replicate this on my machine here. Specifically, checking the debian package search doesn't seem to exhibit issues. Where on that page are you seeing the problem?

![screenshot from 2017-11-01 09-18-21](https://user-images.githubusercontent.com/5883565/32281903-c5cfb9dc-bee5-11e7-8321-5b0c420fd485.png)

**Comment by jlacroix82** [comment]
Try it with the dark version of the pop theme. I'd take a screenshot of it, but it actually corrects itself when I don't have focus on the text box. As soon as I click on the page though, I cannot read the text.

**Comment by isantop** [comment]
Issues like this with firefox can't be fixed because firefox tries to inherit platform styling on web widgets, which is a bad idea because of things like this. It will affect any page where the default styling isn't specified by the page's style sheet, and could only be fixed by making entries in the dark theme light colored (which then wouldn't be dark). This does occur in adwaita-dark, and as such actually represents a bug/issue with firefox's rendering.

Screenshot using Adwaita-dark:
![screenshot from 2017-11-01 09-36-36](https://user-images.githubusercontent.com/5883565/32282851-5941f80e-bee8-11e7-8738-945ff44cd688.png)

**Comment by jlacroix82** [comment]
The AWS example I gave, definitely doesn't happen in Adwaita (which was the main point of this bug, not necessarily Debian's search page). In addition, themes such as VimixDark have successfully worked around this issue.

Since Firefox is the default browser on most distributions, my opinion we should give it a try to fix this for everyone. I don't trust Mozilla will care to do so, since we're not the majority.

**Comment by isantop** [comment]
Sorry man, but it's just not possible to style Firefox correctly without breaking many other components of the dark theme. The only recourse would be to not ship the dark theme at all. Here are some upstream bug reports referencing this type of issue: 

https://bugzilla.redhat.com/show_bug.cgi?id=1215471
https://bugzilla.mozilla.org/show_bug.cgi?id=1161056
https://wiki.archlinux.org/index.php/firefox#Unreadable_input_fields_with_dark_GTK.2B_themes
https://addons.mozilla.org/en-US/firefox/addon/text-contrast-for-dark-themes/

**Comment by WatchMkr** [comment]
@isantop what others places in the dark theme would break? Challenges with quality for a dark theme make me question the investment.

**Comment by WatchMkr** [comment]
On the flip side of that, we have customers that use the dark theme because working all day on a light theme kills their eyes.

**Comment by isantop** [comment]
@jlacroix82 So, I had a conversation with @WatchMkr and we reached the conclusion that while Dark Themes are definitely worth the investment, we need to be careful about certain apps (like firefox). While we work on a more definitive fix, there are some great tips for dealing with this problem here: https://wiki.archlinux.org/index.php/firefox#Unreadable_input_fields_with_dark_GTK.2B_themes

The tip about custom userstyles is probably the best way to solve this.

**Comment by jlacroix82** [comment]
Thank you for the information. I can confirm that both the css and .desktop tweaks mentioned in that link work around this issue.

That said, for whatever it may be worth, the VimixDark theme doesn't have this issue. With that theme, I don't need to utilize the above mentioned work-arounds, everything just works. I don't know what they are doing with that theme to make this work, but maybe something there can be used here.

Have you guys considered an official Pop_OS theme for Firefox? That may be a way to implement a fix, and also add branding to Firefox as well.

Thanks!

**Comment by isantop** [comment]
Vimix dark and Pop share nearly identical styling for "Firefox" (both being forks of Flat-Plat/Materia), so I'm not sure what changes between the two. 

Firefox is deprecating support for Firefox themes in version 57, which is due to be stable in just a few weeks.
