### ISSUE TITLE
Notification indicator/"dot" too dark

### ISSUE THREAD

**Issue by DonHugo69** [pop-os/gtk-theme#86]
```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - 3.22.26-1
 * Desktop environment - GNOME
 * Pop version -2.2.3r0
 ```
Using the pop-compact theme.

The small "dot" displayed beside the clock for indication of new messages is shown in black which makes it very hard to read or realize that there is a new message, etc. I don't if this is as intended, but I thought I report it.

![grafik](https://user-images.githubusercontent.com/10484857/33009538-83f7307a-cdd7-11e7-9298-7dafce6d2b3e.png)

**Comment by isantop** [comment]
This doesn't seem to happen here. The dot is white on my system. 
![screenshot from 2017-11-20 09-19-58](https://user-images.githubusercontent.com/5883565/33029147-0e2e088e-cdd5-11e7-9ec7-f3bddcaaa436.png)

**Comment by nana-4** [comment]
Please check the commit: https://github.com/nana-4/materia-theme/commit/cc76ed6727140b213908983b9e818ee568621200

This happens only when `/usr/share/gnome-shell/gnome-shell-thememe.gresource` is replaced.
(Since `message-indicator-symbolic.svg` is not used with ordinary installing the `gnome-shell` themes.)

**Comment by brs17** [comment]
Seeing as this conversation has gone dormant and no response has been made to the most recent comment, I am going to close this issue. Feel free to reopen if additional information can be provided.
